example.property: I AM THE DEFAULT

server.port: 8080

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eurekaserver:8761/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
           
  
  sql:
    init:
      mode: always
      platform: postgres
      
  datasource:
    driver-class-name: org.postgresql.Driver

management.endpoints.enabled-by-default: false
management.endpoint.health:
  enabled: true
  show-details: always

#CIRCUIT BREAKER
resilience4j:
  circuitbreaker:
    instances:
      licensingService:
        register-health-indicator: true
#        ringBufferSizeInClosedState: 5
#        ringBufferSizeInHalfOpenState: 3
        event-consumer-buffer-size: 10
        failure-rate-threshold: 50
        minimum-number-of-calls: 5
        automatic-transition-from-open-to-half-open-enabled: true
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        sliding-window-size: 10
        sliding-window-type: COUNT_BASED
        record-exceptions:
          - org.springframework.web.client.HttpServerErrorException
          - java.io.IOException
          - java.util.concurrent.TimeoutException
          - org.springframework.web.client.ResourceAccessException
      organizationService:
        register-health-indicator: true
#        ringBufferSizeInClosedState: 6
#        ringBufferSizeInHalfOpenState: 4
        wait-duration-in-open-state: 20s
        failure-rate-threshold: 60
        
#RETRY
  retry:
    instances:
      retryLicenseService:
        max-attempts: 5
        wait-duration: 10000
        retry-exceptions:
          - java.util.concurrent.TimeoutException
        
#BULKHEAD
  bulkhead:
    instances:
      bulkheadLicenseService:
        max-concurrent-calls: 20
        max-wait-duration: 2ms
    metrics:
      enabled: true
      
  thread-pool-bulkhead:
    instances:
      bulkheadLicenseService:
        max-thread-pool-size: 1
        core-thread-pool-size: 1
        queue-capacity: 1
        keep-alive-duration: 20ms

#RATE LIMITER     
  ratelimiter:
    instances:
      licenseService:
        timeout-duration: 1000ms
        limit-refresh-period: 5000
        limit-for-period: 5
