example.property: I AM THE DEFAULT

server.port: 8081

eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      default-zone: http://eurekaserver:8761/eureka/

spring:
  jpa:
    hibernate:
      ddl-auto: create
    database: POSTGRESQL
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    defer-datasource-initialization: true
  
  sql:
    init:
      mode: always
      platform: postgres
      
  datasource:
    driver-class-name: org.postgresql.Driver

management.endpoints.enabled-by-default: false
management.endpoint.health:
  enabled: true
  show-details: always